---
version: '3'
services:
  
  ingestion:
    build: ./publisher/ingestion
    container_name: ingestion_service
    ports:
      - '5000:5000'
    depends_on:
      - redis

  delivery:
    build: ./publisher/delivery
    container_name: delivery_service
    ports:
      - '6000:5000'
    depends_on:
      - redis

  consumer1:
    build: ./consumer
    container_name: consumer1
    ports:
      - '7000:5000'
  
  consumer2:
    build: ./consumer
    container_name: consumer2
    ports:
      - '7001:5000'

  consumer3:
    build: ./consumer
    container_name: consumer3
    ports:
      - '7002:5000'

  redis:
    image: redis:latest
    container_name: redis_queue
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
      - data-volume:/data

volumes:
  data-volume: